### ISSUE TITLE
Make smallest boxes smaller?

### ISSUE THREAD

**Issue by daganzdaanda** [Zverik/whodidit#14]
Is it possible to make the smallest box size even smaller? 
In dense cities, this would help to find a changeset more quickly. But I don't know what the computing cost of smaller minimum boxes is, maybe it would slow things down too much?

**Comment by Zverik** [comment]
Tile size is configurable, so it is possible to make boxes smaller. But for the whole world, it would make the database at least 10 times bigger, losing the point of whodidit: having a change tracking tool that doesn't require much resources.

**Comment by daganzdaanda** [comment]
Ouch, that's what I was afraid of. Nevermind then, thank you!
