### ISSUE TITLE
Можно как-то смотреть правки (на карте) всех кроме меня?

### ISSUE THREAD

**Issue by petrovnn** [Zverik/whodidit#18]
Собственно это была самая большая проблема с который я сталкивался всякий раз во время использования. Слышал вроде в RSS можно, но я им практическки не пользуюсь. В мануале не нашел такой опции

![](http://zverik.osm.rambler.ru/whodidit/wdi_guide.gif)

**Comment by Zverik** [comment]
`!petrovnn` в поле User.
