### ISSUE TITLE
Outdated RSS link

### ISSUE THREAD

**Issue by mmd-osm** [Zverik/whodidit#21]
(Originally reported here: https://forum.openstreetmap.org/viewtopic.php?id=62144)

On http://zverik.openstreetmap.ru/whodidit/  the RSS link still points to http://zverik.osm.rambler.ru/whodidit/scripts/rss.php?bbox=... which doesn't seem to be updated anymore

A redirect from  zverik.osm.rambler.ru to the new host would also be cool I guess.

**Comment by Zverik** [comment]
Thanks, I've updated the link. RSS works again. Not sure about the updates though.

**Comment by mmd-osm** [comment]
Thanks a lot for the quick fix, will ask the folks on the forum again what they meant by the broken updates issue.

**Comment by osmtools** [comment]
@Zverik some rss readers expect a rss feed, but if you visit zverik.osm.rambler.ru.... you got an HTTP 200 but no rss content, so the rss readers won't feed it.
i think a HTTP 301 would be better instead of this javascript window url redirection reloading thing

**Comment by Zverik** [comment]
I agree a redirect would be nice. But I have no control over this, sadly :(
